{"name": "用户注册登录删除-预期失败", "status": "skipped", "statusDetails": {"message": "XFAIL xfail示例：预期失败的用例，如存在尚未解决的Bug等\n\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)", "trace": "self = <testcases.scenario_test.test_03_register_login_delete.TestRegLogDelete object at 0x000002D360ED0370>, testcase_data = {'address': '深圳市宝安区', 'admin_pwd': '123456', 'admin_user': 'wintest4', 'except_code': 3004, ...}\n\n    @allure.story(\"用例--注册/登录/删除--预期失败\")\n    @allure.description(\"该用例是针对 注册-登录-删除 场景的测试\")\n    @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"用户注册登录删除-预期失败\")\n    @pytest.mark.negative\n    @pytest.mark.xfail(reason=\"xfail示例：预期失败的用例，如存在尚未解决的Bug等\")\n    @pytest.mark.usefixtures(\"delete_register_user\")\n    def test_user_register_login_delete_fail(self, testcase_data):\n        username = testcase_data[\"username\"]\n        password = testcase_data[\"password\"]\n        telephone = testcase_data[\"telephone\"]\n        sex = testcase_data[\"sex\"]\n        address = testcase_data[\"address\"]\n        admin_user = testcase_data[\"admin_user\"]\n        admin_pwd = testcase_data[\"admin_pwd\"]\n        except_result = testcase_data[\"except_result\"]\n        except_code = testcase_data[\"except_code\"]\n        except_msg = testcase_data[\"except_msg\"]\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = register_user(username, password, telephone, sex, address)\n        step_1(username, password, telephone, sex, address)\n        assert result.success is True, result.error\n>       result = login_user(admin_user, admin_pwd)\n\ntestcases\\scenario_test\\test_03_register_login_delete.py:90: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\noperation\\user.py:92: in login_user\n    if res.json()[\"code\"] == 0:\nF:\\Virtualenv\\pytest_evn\\lib\\site-packages\\requests\\models.py:897: in json\n    return complexjson.loads(self.text, **kwargs)\nF:\\Python\\lib\\json\\__init__.py:346: in loads\n    return _default_decoder.decode(s)\nF:\\Python\\lib\\json\\decoder.py:337: in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <json.decoder.JSONDecoder object at 0x000002D35EE2FCD0>\ns = '<!doctype html>\\n<html lang=en>\\n  <head>\\n    <title>redis.exceptions.ConnectionError: Error 10061 connecting to 127...message(e))\\nredis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. 由于目标计算机积极拒绝，无法连接。.\\n\\n\\n-->\\n'\nidx = 0\n\n    def raw_decode(self, s, idx=0):\n        \"\"\"Decode a JSON document from ``s`` (a ``str`` beginning with\n        a JSON document) and return a 2-tuple of the Python\n        representation and the index in ``s`` where the document ended.\n    \n        This can be used to decode a JSON document from a string that may\n        have extraneous data at the end.\n    \n        \"\"\"\n        try:\n            obj, end = self.scan_once(s, idx)\n        except StopIteration as err:\n>           raise JSONDecodeError(\"Expecting value\", s, err.value) from None\nE           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nF:\\Python\\lib\\json\\decoder.py:355: JSONDecodeError"}, "description": "该用例是针对 注册-登录-删除 场景的测试", "steps": [{"name": "步骤1 ==>> 注册用户", "status": "passed", "parameters": [{"name": "username", "value": "'测试test'"}, {"name": "password", "value": "'123456'"}, {"name": "telephone", "value": "'13599999999'"}, {"name": "sex", "value": "'1'"}, {"name": "address", "value": "'深圳市宝安区'"}], "start": 1667673738072, "stop": 1667673738072}], "attachments": [{"name": "log", "source": "a677851c-dac8-430e-9e23-03b30c4e7fae-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "885ed263-b3d7-4d24-a461-96e18c36ad81-attachment.txt", "type": "text/plain"}], "start": 1667673738059, "stop": 1667673740260, "uuid": "e0b2feb8-73f2-4669-a91e-8d8152665bd7", "historyId": "7164a98ce91bd9f479af2fa0b0f95820", "testCaseId": "b7d06749c352697ac0c07e2d04f5e9d2", "fullName": "testcases.scenario_test.test_03_register_login_delete.TestRegLogDelete#test_user_register_login_delete_fail", "labels": [{"name": "severity", "value": "minor"}, {"name": "feature", "value": "场景：用户注册-用户登录-删除用户"}, {"name": "story", "value": "用例--注册/登录/删除--预期失败"}, {"name": "epic", "value": "针对业务场景的测试"}, {"name": "tag", "value": "@pytest.mark.usefixtures('delete_register_user')"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='xfail示例：预期失败的用例，如存在尚未解决的Bug等')"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "testcases.scenario_test"}, {"name": "suite", "value": "test_03_register_login_delete"}, {"name": "subSuite", "value": "TestRegLogDelete"}, {"name": "host", "value": "WIN-131NOPQGO9B"}, {"name": "thread", "value": "9124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.scenario_test.test_03_register_login_delete"}], "links": [{"type": "test_case", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应BUG的链接地址"}]}